# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask_semenova_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask_semenova_app.Profile', verbose_name='answer_author'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(verbose_name='is_correct'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(verbose_name='answer_text'),
        ),
        migrations.AlterField(
            model_name='like',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask_semenova_app.Profile', verbose_name='like_from'),
        ),
        migrations.AlterField(
            model_name='like',
            name='to_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask_semenova_app.Question', verbose_name='like_to'),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask_semenova_app.Profile', verbose_name='question_author'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='question_text'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=20, verbose_name='tag'),
        ),
    ]
