# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_semenova_app', '0003_auto_20161114_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
