# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask_semenova_app', '0004_auto_20161114_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ask_semenova_app.Question', verbose_name='answer_to'),
            preserve_default=False,
        ),
    ]
