# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_semenova_app', '0005_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.IntegerField(verbose_name='rate'),
        ),
    ]
