# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ask_semenova_app', '0007_question_add_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='to_question',
        ),
        migrations.AddField(
            model_name='like',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, max_length=30, verbose_name='question_title'),
        ),
    ]
