# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 13:25
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ask_semenova_app', '0009_answer_add_time'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('questions', django.db.models.manager.Manager()),
            ],
        ),
    ]
