# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ask_semenova_app', '0010_auto_20161115_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='answer_rating'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='rating'),
        ),
        migrations.AddField(
            model_name='profile',
            name='registration_data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='question_rating'),
        ),
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.SmallIntegerField(verbose_name='value'),
        ),
    ]
