# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_semenova_app', '0012_auto_20161115_2224'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question_my',
            new_name='Question',
        ),
    ]
