# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import djorm_pgfulltext.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ask_semenova_app', '0014_auto_20161116_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='search_index',
            field=djorm_pgfulltext.fields.VectorField(db_index=True, default='', editable=False, null=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.jpg', null=True, upload_to='avatars/'),
        ),
    ]
