# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_semenova_app', '0015_auto_20161219_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='search_index',
        ),
    ]
